//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, F")]
        public global::Shortcut.Hotkey Key_0 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_0"]));
            }
            set {
                this["Key_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, C")]
        public global::Shortcut.Hotkey Key_1 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_1"]));
            }
            set {
                this["Key_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, V")]
        public global::Shortcut.Hotkey Key_2 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_2"]));
            }
            set {
                this["Key_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, B")]
        public global::Shortcut.Hotkey Key_3 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_3"]));
            }
            set {
                this["Key_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, N")]
        public global::Shortcut.Hotkey Key_4 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_4"]));
            }
            set {
                this["Key_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, H")]
        public global::Shortcut.Hotkey Key_5 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_5"]));
            }
            set {
                this["Key_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, T")]
        public global::Shortcut.Hotkey Key_6 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_6"]));
            }
            set {
                this["Key_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, G")]
        public global::Shortcut.Hotkey Key_7 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_7"]));
            }
            set {
                this["Key_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control, V")]
        public global::Shortcut.Hotkey Key_8 {
            get {
                return ((global::Shortcut.Hotkey)(this["Key_8"]));
            }
            set {
                this["Key_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Leap_0 {
            get {
                return ((string)(this["Leap_0"]));
            }
            set {
                this["Leap_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Leap_1 {
            get {
                return ((string)(this["Leap_1"]));
            }
            set {
                this["Leap_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Leap_2 {
            get {
                return ((string)(this["Leap_2"]));
            }
            set {
                this["Leap_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Leap_3 {
            get {
                return ((string)(this["Leap_3"]));
            }
            set {
                this["Leap_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Myo_0 {
            get {
                return ((string)(this["Myo_0"]));
            }
            set {
                this["Myo_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Myo_1 {
            get {
                return ((string)(this["Myo_1"]));
            }
            set {
                this["Myo_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Myo_2 {
            get {
                return ((string)(this["Myo_2"]));
            }
            set {
                this["Myo_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Myo_3 {
            get {
                return ((string)(this["Myo_3"]));
            }
            set {
                this["Myo_3"] = value;
            }
        }
    }
}
